USE [master]
GO

/****** Object:  Database [Programming_Technologies]    Script Date: 21/05/2022 18:49:40 ******/
DROP DATABASE [Programming_Technologies]
GO

/****** Object:  Database [Programming_Technologies]    Script Date: 21/05/2022 18:49:40 ******/
CREATE DATABASE [Programming_Technologies]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Programming_Technologies', FILENAME = N'Programming_Technologies.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Programming_Technologies_log', FILENAME = N'Programming_Technologies_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Programming_Technologies].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Programming_Technologies] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Programming_Technologies] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Programming_Technologies] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Programming_Technologies] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Programming_Technologies] SET ARITHABORT OFF 
GO

ALTER DATABASE [Programming_Technologies] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Programming_Technologies] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Programming_Technologies] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Programming_Technologies] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Programming_Technologies] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Programming_Technologies] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Programming_Technologies] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Programming_Technologies] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Programming_Technologies] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Programming_Technologies] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Programming_Technologies] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Programming_Technologies] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Programming_Technologies] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Programming_Technologies] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Programming_Technologies] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Programming_Technologies] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Programming_Technologies] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Programming_Technologies] SET RECOVERY FULL 
GO

ALTER DATABASE [Programming_Technologies] SET  MULTI_USER 
GO

ALTER DATABASE [Programming_Technologies] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Programming_Technologies] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Programming_Technologies] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Programming_Technologies] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Programming_Technologies] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Programming_Technologies] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Programming_Technologies] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Programming_Technologies] SET  READ_WRITE 
GO


USE [Programming_Technologies]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[catalog](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[author] [varchar](100) NOT NULL,
	[title] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[action](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](100) NOT NULL,
	[stateId] [int] NOT NULL,
	[personId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[action]  WITH CHECK ADD FOREIGN KEY([personId])
REFERENCES [dbo].[person] ([id])
GO

ALTER TABLE [dbo].[action]  WITH CHECK ADD FOREIGN KEY([stateId])
REFERENCES [dbo].[state] ([id])
GO


CREATE TABLE [dbo].[person](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](100) NOT NULL,
	[surname] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



CREATE TABLE [dbo].[state](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[book] [int] NOT NULL,
	[available] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[state]  WITH CHECK ADD FOREIGN KEY([book])
REFERENCES [dbo].[catalog] ([id])
GO

